@server = http://localhost:3000

# 모든 게시물 조회
GET {{server}}/blog

### 게시물 작성
POST {{server}}/blog
Content-Type: application/json

{
    "title": "제목입니다.",
    "content": "내용입니다.",
    "name": "정수현"
}

### 게시물 하나 조회
GET {{server}}/blog/1

### 게시물 삭제
DELETE {{server}}/blog/2

### 게시물 수정
PUT {{server}}/blog/3
Content-Type: application/json

{
    "title": "수정된 제목입니다.",
    "content": "수정된 내용입니다.",
    "name": "수정된 이름입니다."
}