@server = http://localhost:3000

### 회원 가입
POST {{server}}/auth/register
content-type: application/json

{
    "email": "andy1@podo.com",
    "password": "1234",
    "username": "andy"
}


### 로그인
POST {{server}}/auth/login
content-type: application/json

{
    "email": "andy1@podo.com",
    "password": "1234"
}


### 로그인 2 : LoginGuard
POST {{server}}/auth/login2
content-type: application/json

{
    "email": "andy1@podo.com",
    "password": "1234"
}

### Guard 테스트
GET {{server}}/auth/test-guard