@server = http://localhost:3000/user

### 유저 생성
POST {{server}}/create
Content-Type: application/json

{
    "username": "andy",
    "pw": "test1234",
    "email": "andy@podo.com"
}

### 유저 정보 찾기
GET {{server}}/getUser/andy@podo.com

### 유저 정보 업데이트
PUT {{server}}/update/andy@podo.com
Content-Type: application/json

{
    "email": "andy@podo.com",
    "username": "andy2",
    "pw": "test12345"
}

### 유저 삭제
DELETE {{server}}/delete/andy@podo.com


### 잘못된 이메일과 이름 타입을 입력해보기
POST {{server}}/create
Content-Type: application/json

{
    "email": "andypodocom",
    "username": 5,
    "pw": "test1234"
}