### 유저 생성
POST http://localhost:3000/user/create
Content-Type: application/json

{
    "username": "andy",
    "password": "test124",
    "email": "andy@podo.com"
}

### 유저 정보 찾기
GET http://localhost:3000/user/getUser/andy@podo.com